---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: frontend
      containers:
        - image: fl64/hl2022-app:latest
          imagePullPolicy: Always
          name: backend
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: BACKEND_ADDR
              value: http://backend:8000
            - name: AUTOREFRESH_ENABLE
              value: "false"
            - name: AUTOREFRESH_INTERVAL
              value: "3"
            - name: HISTORY_SIZE
              value: "5"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    service: frontend
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8000
  selector:
    app: frontend

