---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grpc-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
  labels:
    app: grpc-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      serviceAccountName: grpc-server
      containers:
        - name: grpc-server
          image: techdozo/grpc-lb-server:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-server-service
  labels:
    app: grpc-server
    service: grpc-server
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8001
  selector:
    app: grpc-server
