---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: baz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baz
  labels:
    app: baz
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baz
  template:
    metadata:
      labels:
        app: baz
    spec:
      serviceAccountName: baz
      containers:
      - name: app
        image: docker.io/istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: baz
  labels:
    app: baz
    service: baz
spec:
  ports:
  - port: 80
    name: http
    targetPort: 5000
  selector:
    app: baz

