---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: outcast
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: outcast
  labels:
    app: outcast
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outcast
  template:
    metadata:
      labels:
        app: outcast
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: outcast
      containers:
      - name: app
        image: docker.io/istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: outcast
  labels:
    app: outcast
    service: outcast
spec:
  ports:
  - port: 80
    name: http
    targetPort: 5000
  selector:
    app: outcast

