---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
  labels:
    app: bar
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bar
  template:
    metadata:
      labels:
        app: bar
    spec:
      serviceAccountName: bar
      containers:
      - name: app
        image: docker.io/istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: bar
  labels:
    app: bar
    service: bar
spec:
  ports:
  - port: 80
    name: http
    targetPort: 5000
  selector:
    app: bar

