---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      serviceAccountName: client
      terminationGracePeriodSeconds: 0
      containers:
      - name: client
        image: curlimages/curl
        command:
        - sh
        - -c
        - while :; do curl -sS productpage:9080/productpage | grep -o "<title>.*</title>"; sleep 1; done
        imagePullPolicy: IfNotPresent
---
