---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loop-curl-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loop-curl-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loop-curl-client
  template:
    metadata:
      labels:
        app: loop-curl-client
    spec:
      serviceAccountName: loop-curl-client
      terminationGracePeriodSeconds: 0
      containers:
      - name: loop-curl-client
        image: curlimages/curl
        command:
        - sh
        - -c
        - while :; do curl -s productpage:9080/productpage | grep -o "<title>.*</title>"; sleep 1; done
        imagePullPolicy: IfNotPresent
---
