---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  labels:
    app: admin
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      serviceAccountName: admin
      containers:
      - name: app
        image: docker.io/istio/examples-helloworld-v2
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: admin
  labels:
    app: admin
    service: admin
spec:
  ports:
  - port: 80
    name: http
    targetPort: 5000
  selector:
    app: admin

