---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: front
spec:
  host: front
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 10
        maxConnectionDuration: 10ms
      http:
        maxRequestsPerConnection: 3
