---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: ip-flant-ru
spec:
  hosts:
  - ip.flant.ru
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
