---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: authz
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/lab-authz/sa/client-good"]

