---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: front
spec:
  hosts:
  - front
  http:
  - match:
    - headers:
       cookie:
         regex: "^(.*;?)*(user_type=tester)(;.*)*"
    route:
    - destination:
        host: front-v2
  - route:
    - destination:
        host: front-v1
