apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front
spec:
  ingressClassName: nginx
  rules:
  - host: lab-ingress-front.thebox.polovov.hf.flant.com
    http:
      paths:
      - backend:
          service:
            name: front
            port:
              name: http
        path: /
        pathType: Prefix
