---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: front
spec:
  hosts:
  - front
  http:
  - match:
    - uri:
        prefix: "/admin"
    rewrite:
      uri: "/hello"
    route:
    - destination:
        host: admin
  - route:
    - destination:
        host: front
