---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: client-good
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-good
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-good
  template:
    metadata:
      labels:
        app: client-good
    spec:
      serviceAccountName: client-good
      terminationGracePeriodSeconds: 0
      containers:
      - name: client-good
        image: curlimages/curl
        command: ["/bin/sleep", "infinity"]
        imagePullPolicy: IfNotPresent
---
