---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: authz
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: ["lab-authz", "d8-ingress-nginx"]
