apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lab-lb-grpc
resources:
- ../../base

patches:
  - patch: |-
      - op: add
        path: /metadata/labels
        value: {"istio-injection": "enabled"}
    target:
      kind: Namespace
      name: lab-lb-grpc
