apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lab-lb-grpc
resources:
- ../../base

patches:
 - target:
      kind: Namespace
      name: lab-lb-grpc
    patch: |-
      - op: add
        path: /metadata/labels
        value: {"istio-injection": "enabled"}
