apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lab-bookinfo-bad
resources:
- ../../base
- namespace.yaml

images:
- name: docker.io/istio/examples-bookinfo-details-v1
  newName: docker.io/driusha/examples-bookinfo-details-v1
  newTag: "0.1"
- name: docker.io/istio/examples-bookinfo-ratings-v1
  newName: docker.io/driusha/examples-bookinfo-ratings-v1
  newTag: "0.1"
- name: docker.io/istio/examples-bookinfo-reviews-v1
  newName: docker.io/driusha/examples-bookinfo-reviews-v1
  newTag: "0.1"
- name: docker.io/istio/examples-bookinfo-reviews-v2
  newName: docker.io/driusha/examples-bookinfo-reviews-v2
  newTag: "0.1"
- name: docker.io/istio/examples-bookinfo-reviews-v3
  newName: docker.io/driusha/examples-bookinfo-reviews-v3
  newTag: "0.1"
- name: docker.io/istio/examples-bookinfo-productpage-v1
  newName: docker.io/driusha/examples-bookinfo-productpage-v1
  newTag: "0.1"
