---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: front
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  labels:
    app: front
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      serviceAccountName: front
      containers:
      - name: app
        image: docker.io/istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: front
  labels:
    app: front
    service: front
spec:
  ports:
  - port: 80
    name: http
    targetPort: 5000
  selector:
    app: front

